### ISSUE TITLE
Add functionality for a repeating alarm

### ISSUE THREAD

**Issue by jeffnyauke** [CarterChen247/AlarmScheduler#4]

**Comment by CarterChen247** [comment]
Hi @jeffnyauke, would you please describe your request more precisely?

**Comment by jeffnyauke** [comment]
@CarterChen247 Add a way to make an alarm repeat eg. every day at 8 a.m. for five days. Currently, I can only set one alarm.

**Comment by jeffnyauke** [comment]
Did you understand the issue @CarterChen247

**Comment by CarterChen247** [comment]
Hi @jeffnyauke,

Thanks for your suggestion. However, the goal of AlarmScheduler is to remain light weight, focusing on providing exact alarm settings. For the requirement of repeating alarms, it's recommended to create your own custom AlarmTask to achieve this functionality.

**Comment by CarterChen247** [comment]
Since there hasn't been any further discussion or activity on this issue for quite some time, we are marking it as closed. If you still encounter the same problem or have any other concerns, feel free to reopen this issue, and we'll be happy to continue the discussion and provide support. Thank you!
